
clean:
	rm blinky_boot.bin
	rm blinky_boot_crc.bin
	rm blinky_boot.elf
	rm blinky_boot.list
	rm blinky_boot.o

distclean:
	@rm -f blinky_boot.bin
	@rm -f blinky_boot_crc.bin
	@rm -f blinky_boot.elf
	@rm -f blinky_boot.list
	@rm -f blinky_boot.o

# end.
