
clean:
	rm launchpad_boot.bin
	rm launchpad_boot_crc.bin
	rm launchpad_boot.elf
	rm launchpad_boot.list  
	rm launchpad_boot.o

distclean:
	@rm -f launchpad_boot.bin
	@rm -f launchpad_boot_crc.bin
	@rm -f launchpad_boot.elf
	@rm -f launchpad_boot.list  
	@rm -f launchpad_boot.o

# end.

